env:
  - GHCVER=7.6.2
  - GHCVER=7.6.3
  - GHCVER=head
 
matrix:
  allow_failures:
    - env: GHCVER=head

before_install:
  - sudo add-apt-repository -y ppa:hvr/ghc
  - sudo apt-get update
  - sudo apt-get install cabal-install-1.18 ghc-$GHCVER
  - export PATH=/opt/ghc/$GHCVER/bin:$PATH

install:
  - cabal-1.18 update
  - cabal-1.18 install --enable-tests --enable-benchmarks --only-dependencies

script:
  - cabal-1.18 configure --enable-tests --enable-benchmarks -v2
  - cabal-1.18 build
  - cabal-1.18 test
  - cabal-1.18 check
  - cabal-1.18 sdist
